### ISSUE TITLE
Can't download php runtime

### ISSUE THREAD

**Issue by unk0wn-u53r** [RikudouSage/GogDownloader#18]
Issue: After I started the setup-file, I got a error message, that the setup can't download the php runtime.

What I tried: Installed PHP manually but the program doesn't open (correct path proofed with "php -v" in CMD)
![Screenshot 2024-10-11 233544](https://github.com/user-attachments/assets/3696c554-101a-4ecb-be22-4b44f1624e12)

**Comment by RikudouSage** [comment]
Should be fixed for now,  I didn't realize they're deleting the old releases as new ones get created. I'll host the file somewhere myself so it doesn't happen again.

**Comment by RikudouSage** [comment]
Hmm, perhaps your country is one of those that blocks https://catbox.moe which I use as a fallback URL in case the official link gets dead (which happens from time to time).

Do you know of any file sharing server which lets you directly download files and is not blocked in your country?

I've released 1.6.7 which has a working primary link now, but it's likely it's gonna happen again in the future.

**Comment by RikudouSage** [comment]
I've released v1.6.8 which contains another fallback URL that will be used as a last resort, this time to my custom server.
