### ISSUE TITLE
Downloading games with a dot ('.') at the end of the title fails

### ISSUE THREAD

**Issue by jfuerter** [RikudouSage/GogDownloader#20]
OS: Windows 11 (haven't tried any other)
Version: 1.6.5
Examples: 
- Anno 1503 A.D.
- Anno 1602 A.D.
- Anno 1701 A.D.

The download fails with a permission denied exception. I assume due to the fact, that windows doesn't accept a dot at the end of a directory name.

I fixed it for me with the following change by cutting all trailing dots from the title. I have to admit I didn't analyse your coding style so I'm sorry if it's not a match and you can't just use the change as given below.

Anyway, thanks a lot for all the work you invested in this tool, it came to me quite handy!

File:
C:\Users\julian\AppData\Local\Programs\GOG Downloader\src\Trait\TargetDirectoryTrait.php

Code:
```
<?php

namespace App\Trait;

use App\DTO\GameDetail;
use Symfony\Component\Console\Input\InputInterface;

trait TargetDirectoryTrait
{
    private function getTargetDir(InputInterface $input, GameDetail $game, ?string $subdirectory = null): string
    {
        $dir = $input->getArgument('directory');
        if (PHP_OS_FAMILY === 'Windows') {
            if (!preg_match('/^[a-zA-Z]:\\\\/', $dir)) {
                $dir = getcwd() . '/' . $dir;
            }
        } else {
            if (!str_starts_with($dir, '/') && !preg_match('@^[0-9a-zA-Z.]+://.+$@', $dir)) {
                $dir = getcwd() . '/' . $dir;
            }
        }

        $title = preg_replace('@[^a-zA-Z-_0-9.]@', '_', $game->title);
        $title = preg_replace('@_{2,}@', '_', $title);

        // fix for a dot at the end of the game title
        while (str_ends_with($title, '.')) {
            $title = substr($title, 0, -1);
        }

        $dir = "{$dir}/{$title}";
        if ($subdirectory !== null) {
            $dir .= "/{$subdirectory}";
        }

        return $dir;
    }
}

```

**Comment by RikudouSage** [comment]
Thank you! Released a version with the fix, it should be available shortly.

**Comment by jfuerter** [comment]
Thanks for the fast fix! Btw your fix is way better than mine. ;)
