### ISSUE TITLE
should this token be public ? 

### ISSUE THREAD

**Issue by xiro-codes** [RikudouSage/GogDownloader#4]
https://github.com/RikudouSage/GogDownloader/blob/7650baf9cca1608fc2ea443d19a7d6e74e6bdbc0/src/Service/AuthenticationManager.php#L32

**Comment by xiro-codes** [comment]
https://github.com/RikudouSage/GogDownloader/blob/7650baf9cca1608fc2ea443d19a7d6e74e6bdbc0/src/Service/AuthenticationManager.php#L33C1-L33C107

**Comment by RikudouSage** [comment]
Well, in theory it shouldn't, but this one is a leaked client id and secret from GOG themselves and is publicly known, not some kind of my own client id or secret.

Given the fact that it's been used by apps around the world and GOG hasn't done anything about it, they presumably are fine with people using it that way, even if it's not a use endorsed by them.

**Comment by xiro-codes** [comment]
oh so i can just reuse it for my own downloader. cool
