### ISSUE TITLE
Config saving but not reading?

### ISSUE THREAD

**Issue by noplanman** [RikudouSage/GogDownloader#7]
First of all, thanks for this project! :clap: :tada: 

When saving the download path with `app.php config download-path /wherever/this/goes"` I can see the value is correctly saved in the database file.

However, when I then run `app.php config` it shows the value as not set, and consequently it also doesn't apply the correct path as the download destination.

Had a quick look at the code but couldn't see why this is happening. The database file is the correct one.

Any idea why this could be happening?

**Comment by RikudouSage** [comment]
Thanks for the report, it has been fixed.
